### ISSUE TITLE
求助打包的问题

### ISSUE THREAD

**Issue by jianghr-rr** [jkiss/SPA-React-Boilerplate#1]
最近在倒腾vendor文件过大的问题，有思路可以共享下
我现在的思路是把vendor分包，然后gzip压缩
分包的思路是：react单独打出一个，要是用了antd又打一个
现在的问题是我react单独打包成功了，但是再引入一个antd想单独打包却把antd打包到了每个commons里～
下面是我的代码
`cacheGroups: {
            default: {
                minChunks: 2,
                priority: -20,
                reuseExistingChunk: true,
            },
            'react-vendors': {
                name: 'react-vendors',
                test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
                // test: /node_modules/ ,  //mac
                priority: -8
            }, 
            vendors: {
                name: 'vendors',
                test: /[\\/]node_modules[\\/]/,
                // test: /node_modules/ ,  //mac
                priority: -10
            }, 
            commons: {
                name: "commons",
                test: /[\\/]src[\\/]/,
                priority: -30
            }
        }`

![image](https://user-images.githubusercontent.com/5285480/50746904-3cf57d00-126c-11e9-8093-4f2b97687a08.png)

我要是再写一个
`
            'antd-vendors': {
                name: 'antd-vendors',
                test: /[\\/]node_modules[\\/](antd-mobile)[\\/]/,
                // test: /node_modules/ ,  //mac
                priority: -9
            }, `

![image](https://user-images.githubusercontent.com/5285480/50747003-a7a6b880-126c-11e9-94e5-acf7d2f5ee8b.png)

没啥头绪啊 毕老师

**Comment by jkiss** [comment]
我的理解是 **cacheGroups** 类似分组过滤器，模块符合哪个规则就归到哪个 **splitChunk** 下面，我也尝试了一下单独打包 **antd**：
```
'antd-vendors': { 
     name: false, 
     test: /[\\/]node_modules[\\/]antd[\\/]/,
     priority: -9 
}
```

然后我在业务代码引入了一个**Button**：
```
import { Button } from 'antd'
```

效果如下图：
![image](https://user-images.githubusercontent.com/3231326/50818805-24b45980-1363-11e9-9786-304aeddfae03.png)

**Comment by jianghr-rr** [comment]
今天又倒腾了下（多入口的时候， webpack4的optimization）
**第一次分包的时候：**
    代码：
         
![image](https://user-images.githubusercontent.com/5285480/51222468-d3b2ef80-1978-11e9-818c-be9a4a3a8924.png)
    效果：
    
![image](https://user-images.githubusercontent.com/5285480/51222525-1379d700-1979-11e9-874e-ad9eb84a9fd4.png)
**第二次分包的时候**
    代码：
        
![image](https://user-images.githubusercontent.com/5285480/51222553-3310ff80-1979-11e9-881a-fd1cb3f9b9c8.png)
    效果：
        
![image](https://user-images.githubusercontent.com/5285480/51222573-47ed9300-1979-11e9-89ae-9657afcb5014.png)

其实就是想要再出一个单独的antd的包的效果
